apiVersion: v1
kind: Secret
metadata:
  name: symfony-shop-secrets
type: Opaque
stringData:
  APP_SECRET: "REPLACE_WITH_STRONG_APP_SECRET"
  DATABASE_URL: "mysql://REPLACE_DB_USER:REPLACE_DB_PASSWORD@service-symfony-shop-db:3306/REPLACE_DB_NAME"
  DATABASE_REPLICA_URL: "mysql://REPLACE_DB_USER:REPLACE_DB_PASSWORD@service-symfony-shop-db-read:3306/REPLACE_DB_NAME"
  MESSENGER_TRANSPORT_DSN: "amqp://REPLACE_RABBITMQ_USER:REPLACE_RABBITMQ_PASSWORD@service-symfony-shop-rabbitmq:5672/%2f/async"
  MESSENGER_CHECKOUT_TRANSPORT_DSN: "amqp://REPLACE_RABBITMQ_USER:REPLACE_RABBITMQ_PASSWORD@service-symfony-shop-rabbitmq:5672/%2f/checkout_async"
  MESSENGER_FAILED_TRANSPORT_DSN: "amqp://REPLACE_RABBITMQ_USER:REPLACE_RABBITMQ_PASSWORD@service-symfony-shop-rabbitmq:5672/%2f/failed"
  KEDA_RABBITMQ_HOST: "amqp://REPLACE_RABBITMQ_USER:REPLACE_RABBITMQ_PASSWORD@service-symfony-shop-rabbitmq:5672/%2f"
  PAYPAL_CLIENT_ID: "REPLACE_WITH_PAYPAL_CLIENT_ID"
  PAYPAL_CLIENT_SECRET: "REPLACE_WITH_PAYPAL_CLIENT_SECRET"
