apiVersion: v1
kind: Secret
metadata:
  name: symfony-shop-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: REPLACE_WITH_STRONG_ROOT_PASSWORD
  MYSQL_DATABASE: REPLACE_WITH_DB_NAME
  MYSQL_USER: REPLACE_WITH_DB_USER
  MYSQL_PASSWORD: REPLACE_WITH_DB_PASSWORD
  MYSQL_REPLICATION_USER: REPLACE_WITH_REPL_USER
  MYSQL_REPLICATION_PASSWORD: REPLACE_WITH_REPL_PASSWORD
