apiVersion: v1
kind: ConfigMap
metadata:
  name: frankenphp-config
data:
  Caddyfile: |
    {
      auto_https off
      admin off
      frankenphp {
        {$FRANKENPHP_CONFIG}
      }
    }

    :80 {
      root * /app/public
      encode zstd br gzip

      request_body {
        max_size 50MB
      }

      @assets path /assets/*
      header @assets Cache-Control "no-store, no-cache, must-revalidate, max-age=0"

      php_server
    }
