apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: symfony-worker-rabbitmq-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: symfony-shop-secrets
      key: KEDA_RABBITMQ_HOST
