apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: symfony-shop-worker-queue-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: symfony-shop-worker
  pollingInterval: 15
  cooldownPeriod: 120
  minReplicaCount: 2
  maxReplicaCount: 12
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: async
        mode: QueueLength
        value: "20"
        activationValue: "1"
      authenticationRef:
        name: symfony-worker-rabbitmq-auth
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: checkout_async
        mode: QueueLength
        value: "20"
        activationValue: "1"
      authenticationRef:
        name: symfony-worker-rabbitmq-auth
