apiVersion: v1
kind: Pod
metadata:
  name: mysql-repair
  namespace: default
  labels:
    app: mysql-repair
spec:
  restartPolicy: Never
  containers:
    - name: shell
      image: mysql:8.0
      command:
        - sh
        - -lc
        - sleep 36000
      volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: symfony-shop-db-pvc
