apiVersion: v1
kind: Secret
metadata:
  name: mysql-exporter-secret
  namespace: default
type: Opaque
stringData:
  DATA_SOURCE_NAME: "REPLACE_DB_USER:REPLACE_DB_PASSWORD@(service-symfony-shop-db:3306)/"
