
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv4
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/html"

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi