# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: '%env(SESSION_HANDLER_DSN)%'
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    http_cache:
        enabled: true
        trace_level: short
        stale_while_revalidate: 60
        stale_if_error: 86400

    rate_limiter:
        checkout_finalize:
            policy: token_bucket
            limit: 10
            rate:
                interval: '1 minute'
                amount: 10
            cache_pool: cache.app

        checkout_callback:
            policy: token_bucket
            limit: 30
            rate:
                interval: '1 minute'
                amount: 30
            cache_pool: cache.app

        api_request:
            policy: fixed_window
            limit: 120
            interval: '1 minute'
            cache_pool: cache.app
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
